stages:
  - Env
  - Build

variables:
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive
  CCACHE_DIR: "${CI_PROJECT_DIR}/ccache"
  CCACHE_UMASK: 000
  CXXFLAGS: "-Werror -Wno-return-type -Wno-deprecated-declarations"
  IGNORE_NOCI: "FALSE"
  FLECSPH_MPI_PROVIDER: ""
  FLECSPH_OPENMPI_VERSION: "4.1.0"
  FLECSPH_OPENMPI_SPEC: "+pmi+legacylaunchers+thread_multiple fabrics=auto"
  FLECSPH_MPICH_VERSION: "3.4.1"
  FLECSPH_MPICH_SPEC: "+slurm+verbs device=ch3"
  FLECSPH_INTEL_VERSION: "19.0.2"
  FLECSPH_CLANG_VERSION: "12.0.1"
  FLECSPH_GCC_VERSION: "9.3.0"
  FLECSPH_SPACK_SPEC: "flecsph@master%gcc@${FLECSPH_GCC_VERSION}"
  FLECSPH_SPACK_REPO: "https://github.com/spack/spack.git"
  FLECSPH_SPACK_REF: "v0.16.2-26c6456"
  SCHEDULER_PARAMETERS: "--nodes=1 --partition=skylake-gold"
before_script:
  - '[ "$(git rev-parse origin/$CI_COMMIT_REF_NAME)" != "$CI_COMMIT_SHA" ] && curl --header "PRIVATE-TOKEN: $MY_CI_API_TOKEN" -X POST https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/cancel'
  - export HOME=${CI_PROJECT_DIR}
  - export TMPDIR=${CI_PROJECT_DIR}
  - unset SPACK_ROOT
  - echo ${CI_RUNNER_TAGS}
  - export FLECSPH_SPACK_SPEC="${FLECSPH_SPACK_SPEC} $([ ${CI_RUNNER_TAGS} == 'darwin-slurm-shared' ] && echo 'target=x86_64')"
  - |
    if [[ ${FLECSPH_MPI_PROVIDER} == 'openmpi' ]];
    then
      export FLECSPH_SPACK_FULL_SPEC="${FLECSPH_SPACK_SPEC} ^${FLECSPH_MPI_PROVIDER}@${FLECSPH_OPENMPI_VERSION}%gcc@${FLECSPH_GCC_VERSION} ${FLECSPH_OPENMPI_SPEC}";
    else
      export FLECSPH_SPACK_FULL_SPEC="${FLECSPH_SPACK_SPEC} ^${FLECSPH_MPI_PROVIDER}@${FLECSPH_MPICH_VERSION}%gcc@${FLECSPH_GCC_VERSION} ${FLECSPH_MPICH_SPEC}";
    fi
  - |
    if [[ -d ${CI_PROJECT_DIR}/spack ]];
    then
      . ${CI_PROJECT_DIR}/spack/share/spack/setup-env.sh;
      spack reindex;
      spack module tcl refresh -y;
      module use ${CI_PROJECT_DIR}/spack/share/spack/modules/`spack arch`;
    fi


.batch_template:
  tags:
    - darwin-slurm-shared
  only:
    - merge_requests
    - master
  artifacts:
    name: "flecsph-${CI_COMMIT_REF_SLUG}-${CI_JOB_NAME}-${CI_JOB_ID}"
    paths:
      - ${CI_PROJECT_DIR}/build
    when: always
    expire_in: 3 hours
  dependencies: []


.env:
  extends: .batch_template
  stage: Env
  artifacts:
    paths:
      - ${CI_PROJECT_DIR}/spack
      - ${CI_PROJECT_DIR}/ristra_spackages
      - ${CI_PROJECT_DIR}/spack_env
  variables:
    GIT_SUBMODULE_STRATEGY: none
  script:
    - cd ${CI_PROJECT_DIR}
    - module load gcc/${FLECSPH_GCC_VERSION}
    - git clone -b ${FLECSPH_SPACK_REF} https://${RISTRA_SPACKAGES_USERNAME}:${RISTRA_SPACKAGES_PASSWORD}@gitlab.lanl.gov/laristra/ristra_spackages.git
    - git clone https://${RISTRA_SPACK_CONFIG_USERNAME}:${RISTRA_SPACK_CONFIG_PASSWORD}@gitlab.lanl.gov/laristra/ristra-spack-configurations.git
    - echo 'Spack Version:' ${FLECSPH_SPACK_REF}
    - git clone ${FLECSPH_SPACK_REPO}
    - cd spack && git checkout ${FLECSPH_SPACK_REF##*-} && cd ${CI_PROJECT_DIR}
    - export SPACK_ARCH=`./spack/bin/spack arch`
    - echo ${SPACK_ARCH}
    - export PLATFORM="${SPACK_ARCH%%-*}"
    - echo ${PLATFORM}
    - mkdir -p ${CI_PROJECT_DIR}/spack/etc/spack/${PLATFORM}
    - cp ${CI_PROJECT_DIR}/ristra-spack-configurations/common/*.yaml ${CI_PROJECT_DIR}/spack/etc/spack/
    - |
      if [[ -d ${CI_PROJECT_DIR}/ristra-spack-configurations/Darwin/${FLECSPH_SPACK_REF%.*} ]];
      then
        cp ${CI_PROJECT_DIR}/ristra-spack-configurations/Darwin/${FLECSPH_SPACK_REF%.*}/*.yaml ${CI_PROJECT_DIR}/spack/etc/spack/${PLATFORM}/;
        cp ${CI_PROJECT_DIR}/ristra-spack-configurations/Darwin/${FLECSPH_SPACK_REF%.*}/public/*.yaml ${CI_PROJECT_DIR}/spack/etc/spack/${PLATFORM}/;
      fi
    - |
      if [[ -f ${CI_PROJECT_DIR}/spack/etc/spack/${PLATFORM}/upstreams.yaml ]];
      then
        export SPACK_MODULES=`awk '/tcl/{print $NF}' ${CI_PROJECT_DIR}/spack/etc/spack/${PLATFORM}/upstreams.yaml`;
        export SPACK_MODULES_ARRAY=($spack_modules);
        for s in "${!SPACK_MODULES_ARRAY[@]}"; do [ ! -d ${SPACK_MODULES_ARRAY[s]} ] && { rm ${CI_PROJECT_DIR}/spack/etc/spack/${PLATFORM}/upstreams.yaml; break; }; done
      fi
    # HPC mirror has cached an older version of flecsi and cinch
    - ${CI_PROJECT_DIR}/spack/bin/spack mirror rm --scope site lanl
    - . ${CI_PROJECT_DIR}/spack/share/spack/setup-env.sh
    - spack repo add --scope site ${CI_PROJECT_DIR}/ristra_spackages/spack-repo
    - spack repo add --scope site ${CI_PROJECT_DIR}/spack-repo
    - spack repo list
    - mkdir -p ${CI_PROJECT_DIR}/spack_env
    - spack env create --without-view -d ${CI_PROJECT_DIR}/spack_env
    - spack env activate -d ${CI_PROJECT_DIR}/spack_env
    - spack dev-build -q ${FLECSPH_SPACK_FULL_SPEC} || ( cat spack-build-out.txt && exit 1 )
    - export FLECSPH_CMD="spack install --show-log-on-error ${FLECSPH_SPACK_FULL_SPEC}"
    - ( echo "$FLECSPH_CMD" && $FLECSPH_CMD )
    - spack module tcl refresh -y
    - spack env loads -r
    - export modName="${CI_PROJECT_DIR}/spack_env/loads"
    - sed -i "1s;^;module load gcc/${FLECSPH_GCC_VERSION}\n;" ${modName}
    - sed -i "1s;^;#%Module\n;" ${modName}

env_openmpi:
  extends: .env
  variables:
    FLECSPH_MPI_PROVIDER: "openmpi"

env_mpich:
  extends: .env
  variables:
    FLECSPH_MPI_PROVIDER: "mpich"

.build:
  extends: .batch_template
  stage: Build
  script:
    - module purge
    - module use ${CI_PROJECT_DIR}/spack_env
    - module load loads # module load compiler, deps, etc.
    - |
      if [[ ${CI_JOB_NAME} =~ "clang" ]];
      then
        module load clang/${FLECSPH_CLANG_VERSION};
      elif [[ ${CI_JOB_NAME} =~ "intel" ]];
      then
        module load intel/${FLECSPH_INTEL_VERSION};
      fi
    - module list
    - echo $CC
    - echo $CXX
    - mpiexec --version
    - nproc
    - echo 'Start building'
    - mkdir -p ${CI_PROJECT_DIR}/build
    - cd ${CI_PROJECT_DIR}/build
    - cmake ../ -DCMAKE_BUILD_TYPE=Debug
    - make 
    - make test

build_openmpi:
  extends: .build
  dependencies: [ env_openmpi ]
  variables:
    FLECSPH_MPI_PROVIDER: "openmpi"

build_mpich:
  extends: .build
  dependencies: [ env_mpich ]
  variables:
    FLECSPH_MPI_PROVIDER: "mpich"
