upstreams:
  public-spack:
    install_tree: /projects/ngc/public/ristra_module_gen/spack-v0.16.2-26c6456/opt/spack
    modules:
      tcl: /projects/ngc/public/ristra_module_gen/spack-v0.16.2-26c6456/share/spack/modules
